# Generated by Django 4.0.4 on 2022-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
