# Generated by Django 4.0.4 on 2022-05-23 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0006_student_image_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
